### ISSUE TITLE
Free plan

### ISSUE THREAD

**Issue by naourass** [Apptha/Marketplace-M2#14]
Is there a Free plan for sellers? Or can we just create a plan with zero fees ?

**Comment by VarunContus** [comment]
Hi Naourass,

There aren't free plans for the sellers. If you want to create the seller with the zero fees, you can enter the seller commission(%) as 0. You can configure it on a Global basis as well as the seller basis.

Also, by default, there is no option to create a seller subscription plan with the zero amount. You need to create the same with the amount greater than zero.

**Comment by naourass** [comment]
I think it is mandatory to have sellers plan with 0 fees for such a solution. I suggest that you add this feature in your new releases !

**Comment by godilite** [comment]
@naourass when I click on manage prodct from seller dashboard I only see a page title "MY Account" is this a bug? Seller cant add product or sell or manage products

**Comment by godilite** [comment]
I'm asking you because the author seems too busy to reply issues
