### ISSUE TITLE
SKU is not available

### ISSUE THREAD

**Issue by naourass** [Apptha/Marketplace-M2#16]
The seller can't add a product, because of SKU validation error.

Stack : PHP 7.2.x, Magento 2.3.1

**Comment by lima195** [comment]
Same problem here, you can fix updating this:
app/code/Apptha/Marketplace/Controller/Product/Skuvalidate.php

changing line(72):
echo $skuCount;

to:

return $this->getResponse()->setBody(json_encode($skuCount));

**Comment by lima195** [comment]
This fix works like a charm with every ajax response in this module
